//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thumbnify.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thumbnify.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Film &amp; Animation ähnelt.
        /// </summary>
        internal static string yt_cat_01 {
            get {
                return ResourceManager.GetString("yt_cat_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autos &amp; Vehicles ähnelt.
        /// </summary>
        internal static string yt_cat_02 {
            get {
                return ResourceManager.GetString("yt_cat_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music ähnelt.
        /// </summary>
        internal static string yt_cat_10 {
            get {
                return ResourceManager.GetString("yt_cat_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pets &amp; Animals ähnelt.
        /// </summary>
        internal static string yt_cat_15 {
            get {
                return ResourceManager.GetString("yt_cat_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sports ähnelt.
        /// </summary>
        internal static string yt_cat_17 {
            get {
                return ResourceManager.GetString("yt_cat_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Movies ähnelt.
        /// </summary>
        internal static string yt_cat_18 {
            get {
                return ResourceManager.GetString("yt_cat_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Travel &amp; Events ähnelt.
        /// </summary>
        internal static string yt_cat_19 {
            get {
                return ResourceManager.GetString("yt_cat_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gaming ähnelt.
        /// </summary>
        internal static string yt_cat_20 {
            get {
                return ResourceManager.GetString("yt_cat_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Videoblogging ähnelt.
        /// </summary>
        internal static string yt_cat_21 {
            get {
                return ResourceManager.GetString("yt_cat_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die People &amp; Blogs ähnelt.
        /// </summary>
        internal static string yt_cat_22 {
            get {
                return ResourceManager.GetString("yt_cat_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comedy ähnelt.
        /// </summary>
        internal static string yt_cat_23 {
            get {
                return ResourceManager.GetString("yt_cat_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entertainment ähnelt.
        /// </summary>
        internal static string yt_cat_24 {
            get {
                return ResourceManager.GetString("yt_cat_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die News &amp; Politics ähnelt.
        /// </summary>
        internal static string yt_cat_25 {
            get {
                return ResourceManager.GetString("yt_cat_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HowTo &amp; Style ähnelt.
        /// </summary>
        internal static string yt_cat_26 {
            get {
                return ResourceManager.GetString("yt_cat_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Education ähnelt.
        /// </summary>
        internal static string yt_cat_27 {
            get {
                return ResourceManager.GetString("yt_cat_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Science &amp; Technology ähnelt.
        /// </summary>
        internal static string yt_cat_28 {
            get {
                return ResourceManager.GetString("yt_cat_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nonprofits &amp; Activism ähnelt.
        /// </summary>
        internal static string yt_cat_29 {
            get {
                return ResourceManager.GetString("yt_cat_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Movies ähnelt.
        /// </summary>
        internal static string yt_cat_30 {
            get {
                return ResourceManager.GetString("yt_cat_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anime/Animation ähnelt.
        /// </summary>
        internal static string yt_cat_31 {
            get {
                return ResourceManager.GetString("yt_cat_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action/Adventure ähnelt.
        /// </summary>
        internal static string yt_cat_32 {
            get {
                return ResourceManager.GetString("yt_cat_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classics ähnelt.
        /// </summary>
        internal static string yt_cat_33 {
            get {
                return ResourceManager.GetString("yt_cat_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comedy ähnelt.
        /// </summary>
        internal static string yt_cat_34 {
            get {
                return ResourceManager.GetString("yt_cat_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Documentary ähnelt.
        /// </summary>
        internal static string yt_cat_35 {
            get {
                return ResourceManager.GetString("yt_cat_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drama ähnelt.
        /// </summary>
        internal static string yt_cat_36 {
            get {
                return ResourceManager.GetString("yt_cat_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Family ähnelt.
        /// </summary>
        internal static string yt_cat_37 {
            get {
                return ResourceManager.GetString("yt_cat_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foreign ähnelt.
        /// </summary>
        internal static string yt_cat_38 {
            get {
                return ResourceManager.GetString("yt_cat_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horror ähnelt.
        /// </summary>
        internal static string yt_cat_39 {
            get {
                return ResourceManager.GetString("yt_cat_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sci-Fi/Fantasy ähnelt.
        /// </summary>
        internal static string yt_cat_40 {
            get {
                return ResourceManager.GetString("yt_cat_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thriller ähnelt.
        /// </summary>
        internal static string yt_cat_41 {
            get {
                return ResourceManager.GetString("yt_cat_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shorts ähnelt.
        /// </summary>
        internal static string yt_cat_42 {
            get {
                return ResourceManager.GetString("yt_cat_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows ähnelt.
        /// </summary>
        internal static string yt_cat_43 {
            get {
                return ResourceManager.GetString("yt_cat_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trailers ähnelt.
        /// </summary>
        internal static string yt_cat_44 {
            get {
                return ResourceManager.GetString("yt_cat_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Private ähnelt.
        /// </summary>
        internal static string yt_private {
            get {
                return ResourceManager.GetString("yt_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Public ähnelt.
        /// </summary>
        internal static string yt_public {
            get {
                return ResourceManager.GetString("yt_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlisted ähnelt.
        /// </summary>
        internal static string yt_unlisted {
            get {
                return ResourceManager.GetString("yt_unlisted", resourceCulture);
            }
        }
    }
}
