//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thumbnify.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thumbnify.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some media parts have not yet finished processing. Do you want to cancel them? ähnelt.
        /// </summary>
        internal static string msg_cancelGraphs {
            get {
                return ResourceManager.GetString("msg_cancelGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete all media files that are already completely processed? ähnelt.
        /// </summary>
        internal static string msg_cleanup {
            get {
                return ResourceManager.GetString("msg_cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new preset? You will lose all unsaved changes. ähnelt.
        /// </summary>
        internal static string msg_createNew {
            get {
                return ResourceManager.GetString("msg_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete all selected actions? ähnelt.
        /// </summary>
        internal static string msg_deleteActions {
            get {
                return ResourceManager.GetString("msg_deleteActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete the selected media part? ähnelt.
        /// </summary>
        internal static string msg_deleteMediaPart {
            get {
                return ResourceManager.GetString("msg_deleteMediaPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete the selected preset? ähnelt.
        /// </summary>
        internal static string msg_deletePreset {
            get {
                return ResourceManager.GetString("msg_deletePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite selected preset? ähnelt.
        /// </summary>
        internal static string msg_overwritePreset {
            get {
                return ResourceManager.GetString("msg_overwritePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter text: ähnelt.
        /// </summary>
        internal static string msg_stringParam {
            get {
                return ResourceManager.GetString("msg_stringParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected account does not have any channels. ähnelt.
        /// </summary>
        internal static string msg_ytNoChannels {
            get {
                return ResourceManager.GetString("msg_ytNoChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel Processing ähnelt.
        /// </summary>
        internal static string title_cancelGraphs {
            get {
                return ResourceManager.GetString("title_cancelGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Media Cleanup ähnelt.
        /// </summary>
        internal static string title_cleanup {
            get {
                return ResourceManager.GetString("title_cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create New preset ähnelt.
        /// </summary>
        internal static string title_createNew {
            get {
                return ResourceManager.GetString("title_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Actions ähnelt.
        /// </summary>
        internal static string title_deleteActions {
            get {
                return ResourceManager.GetString("title_deleteActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Media Part ähnelt.
        /// </summary>
        internal static string title_deleteMediaPart {
            get {
                return ResourceManager.GetString("title_deleteMediaPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Preset ähnelt.
        /// </summary>
        internal static string title_deletePreset {
            get {
                return ResourceManager.GetString("title_deletePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite Preset ähnelt.
        /// </summary>
        internal static string title_overwritePreset {
            get {
                return ResourceManager.GetString("title_overwritePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String Parameter ähnelt.
        /// </summary>
        internal static string title_stringParam {
            get {
                return ResourceManager.GetString("title_stringParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Channels found ähnelt.
        /// </summary>
        internal static string title_ytNoChannels {
            get {
                return ResourceManager.GetString("title_ytNoChannels", resourceCulture);
            }
        }
    }
}
