//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thumbnify.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Nodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nodes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thumbnify.Resources.Nodes", typeof(Nodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compressor ähnelt.
        /// </summary>
        internal static string audio_compressor {
            get {
                return ResourceManager.GetString("audio_compressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Audio ähnelt.
        /// </summary>
        internal static string audio_load {
            get {
                return ResourceManager.GetString("audio_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge Audio ähnelt.
        /// </summary>
        internal static string audio_merge {
            get {
                return ResourceManager.GetString("audio_merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Metadata ähnelt.
        /// </summary>
        internal static string audio_metadata {
            get {
                return ResourceManager.GetString("audio_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normalize Audio ähnelt.
        /// </summary>
        internal static string audio_normalize {
            get {
                return ResourceManager.GetString("audio_normalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resample Audio ähnelt.
        /// </summary>
        internal static string audio_resample {
            get {
                return ResourceManager.GetString("audio_resample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Audio ähnelt.
        /// </summary>
        internal static string audio_save {
            get {
                return ResourceManager.GetString("audio_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convert Date ähnelt.
        /// </summary>
        internal static string convert_date {
            get {
                return ResourceManager.GetString("convert_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebDav Upload ähnelt.
        /// </summary>
        internal static string file_webdav {
            get {
                return ResourceManager.GetString("file_webdav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credentials ähnelt.
        /// </summary>
        internal static string input_credentials {
            get {
                return ResourceManager.GetString("input_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string input_date {
            get {
                return ResourceManager.GetString("input_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mediapart ähnelt.
        /// </summary>
        internal static string input_part {
            get {
                return ResourceManager.GetString("input_part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        internal static string input_path {
            get {
                return ResourceManager.GetString("input_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prefix ähnelt.
        /// </summary>
        internal static string input_prefix {
            get {
                return ResourceManager.GetString("input_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suffix ähnelt.
        /// </summary>
        internal static string input_suffix {
            get {
                return ResourceManager.GetString("input_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temporary Path ähnelt.
        /// </summary>
        internal static string input_temppath {
            get {
                return ResourceManager.GetString("input_temppath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String ähnelt.
        /// </summary>
        internal static string input_text {
            get {
                return ResourceManager.GetString("input_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thumbnail ähnelt.
        /// </summary>
        internal static string input_thumbnail {
            get {
                return ResourceManager.GetString("input_thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio ähnelt.
        /// </summary>
        internal static string mnu_audio {
            get {
                return ResourceManager.GetString("mnu_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convert ähnelt.
        /// </summary>
        internal static string mnu_convert {
            get {
                return ResourceManager.GetString("mnu_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string mnu_delete {
            get {
                return ResourceManager.GetString("mnu_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files ähnelt.
        /// </summary>
        internal static string mnu_files {
            get {
                return ResourceManager.GetString("mnu_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input ähnelt.
        /// </summary>
        internal static string mnu_input {
            get {
                return ResourceManager.GetString("mnu_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operations ähnelt.
        /// </summary>
        internal static string mnu_operations {
            get {
                return ResourceManager.GetString("mnu_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video ähnelt.
        /// </summary>
        internal static string mnu_video {
            get {
                return ResourceManager.GetString("mnu_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Youtube ähnelt.
        /// </summary>
        internal static string mnu_youtube {
            get {
                return ResourceManager.GetString("mnu_youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Combine Path ähnelt.
        /// </summary>
        internal static string op_pathcombine {
            get {
                return ResourceManager.GetString("op_pathcombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Render Thumbnail ähnelt.
        /// </summary>
        internal static string op_renderThumb {
            get {
                return ResourceManager.GetString("op_renderThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Combine Text ähnelt.
        /// </summary>
        internal static string op_stringCombine {
            get {
                return ResourceManager.GetString("op_stringCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace Variables ähnelt.
        /// </summary>
        internal static string op_textReplace {
            get {
                return ResourceManager.GetString("op_textReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account ähnelt.
        /// </summary>
        internal static string param_account {
            get {
                return ResourceManager.GetString("param_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Album ähnelt.
        /// </summary>
        internal static string param_album {
            get {
                return ResourceManager.GetString("param_album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio ähnelt.
        /// </summary>
        internal static string param_audio {
            get {
                return ResourceManager.GetString("param_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio 1 ähnelt.
        /// </summary>
        internal static string param_audio1 {
            get {
                return ResourceManager.GetString("param_audio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio 2 ähnelt.
        /// </summary>
        internal static string param_audio2 {
            get {
                return ResourceManager.GetString("param_audio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitdepth ähnelt.
        /// </summary>
        internal static string param_bitdepth {
            get {
                return ResourceManager.GetString("param_bitdepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        internal static string param_category {
            get {
                return ResourceManager.GetString("param_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Stream ähnelt.
        /// </summary>
        internal static string param_copystream {
            get {
                return ResourceManager.GetString("param_copystream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credentials ähnelt.
        /// </summary>
        internal static string param_credentials {
            get {
                return ResourceManager.GetString("param_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string param_date {
            get {
                return ResourceManager.GetString("param_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string param_description {
            get {
                return ResourceManager.GetString("param_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string param_file {
            get {
                return ResourceManager.GetString("param_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format ähnelt.
        /// </summary>
        internal static string param_format {
            get {
                return ResourceManager.GetString("param_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interpret ähnelt.
        /// </summary>
        internal static string param_interpret {
            get {
                return ResourceManager.GetString("param_interpret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string param_name {
            get {
                return ResourceManager.GetString("param_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        internal static string param_path {
            get {
                return ResourceManager.GetString("param_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playlist ähnelt.
        /// </summary>
        internal static string param_playlist {
            get {
                return ResourceManager.GetString("param_playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Samples ähnelt.
        /// </summary>
        internal static string param_samples {
            get {
                return ResourceManager.GetString("param_samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target Loudness (LUFS) ähnelt.
        /// </summary>
        internal static string param_target_lu {
            get {
                return ResourceManager.GetString("param_target_lu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thumbnail ähnelt.
        /// </summary>
        internal static string param_thumbnail {
            get {
                return ResourceManager.GetString("param_thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        internal static string param_title {
            get {
                return ResourceManager.GetString("param_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL ähnelt.
        /// </summary>
        internal static string param_url {
            get {
                return ResourceManager.GetString("param_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string param_value {
            get {
                return ResourceManager.GetString("param_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video ähnelt.
        /// </summary>
        internal static string param_video {
            get {
                return ResourceManager.GetString("param_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Video ähnelt.
        /// </summary>
        internal static string video_save {
            get {
                return ResourceManager.GetString("video_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add to Playlist ähnelt.
        /// </summary>
        internal static string youtube_addplaylist {
            get {
                return ResourceManager.GetString("youtube_addplaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload Video ähnelt.
        /// </summary>
        internal static string youtube_upload {
            get {
                return ResourceManager.GetString("youtube_upload", resourceCulture);
            }
        }
    }
}
